user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation


test_github:
    resource: '@AppBundle/Controller/'
    type: annotation
